// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ou

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/thunder-id/thunderid/pkg/thunderidengine/common"
)

// NewProjectResolverMock creates a new instance of ProjectResolverMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProjectResolverMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProjectResolverMock {
	mock := &ProjectResolverMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProjectResolverMock is an autogenerated mock type for the ProjectResolver type
type ProjectResolverMock struct {
	mock.Mock
}

type ProjectResolverMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ProjectResolverMock) EXPECT() *ProjectResolverMock_Expecter {
	return &ProjectResolverMock_Expecter{mock: &_m.Mock}
}

// IsProjectExists provides a mock function for the type ProjectResolverMock
func (_mock *ProjectResolverMock) IsProjectExists(ctx context.Context, id string) (bool, *common.ServiceError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IsProjectExists")
	}

	var r0 bool
	var r1 *common.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, *common.ServiceError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *common.ServiceError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*common.ServiceError)
		}
	}
	return r0, r1
}

// ProjectResolverMock_IsProjectExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsProjectExists'
type ProjectResolverMock_IsProjectExists_Call struct {
	*mock.Call
}

// IsProjectExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ProjectResolverMock_Expecter) IsProjectExists(ctx interface{}, id interface{}) *ProjectResolverMock_IsProjectExists_Call {
	return &ProjectResolverMock_IsProjectExists_Call{Call: _e.mock.On("IsProjectExists", ctx, id)}
}

func (_c *ProjectResolverMock_IsProjectExists_Call) Run(run func(ctx context.Context, id string)) *ProjectResolverMock_IsProjectExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProjectResolverMock_IsProjectExists_Call) Return(b bool, serviceError *common.ServiceError) *ProjectResolverMock_IsProjectExists_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *ProjectResolverMock_IsProjectExists_Call) RunAndReturn(run func(ctx context.Context, id string) (bool, *common.ServiceError)) *ProjectResolverMock_IsProjectExists_Call {
	_c.Call.Return(run)
	return _c
}
